---
  
- hosts: all
  vars:
    ansible_host_key_checking: false ##If you get an error about hosts not trusted
  become: true
  become_user: root

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes
